ALTER TABLE child ADD blood_glucose_at_diagnosis int(11) not null;
ALTER TABLE child ADD blood_glucose_value float default null;
ALTER TABLE child ADD blood_glucose_units int(11) default null;
ALTER TABLE child ADD hba1c_at_diagnosis int(11) not null;
ALTER TABLE child ADD hba1c_percentage float default null;
ALTER TABLE child ADD hba1c_method int(11) default null;
ALTER TABLE child ADD ketoacidosis_at_diagnosis int(11) not null;
ALTER TABLE child ADD polyuria_at_diagnosis int(11) not null;
ALTER TABLE child ADD thirst_at_diagnosis int(11) not null;
ALTER TABLE child ADD weight_loss_at_diagnosis int(11) not null;
ALTER TABLE child ADD weight_at_diagnosis int(11) not null;
ALTER TABLE child ADD weight_at_diagnosis_value float default null;
ALTER TABLE child ADD height_at_diagnosis int(11) not null;
ALTER TABLE child ADD height_at_diagnosis_value float default null;
ALTER TABLE child ADD type_one_in_family int(11) not null;
ALTER TABLE child ADD type_one_relatives_details varchar(255) default null;
ALTER TABLE child ADD type_two_in_family int(11) not null;
ALTER TABLE child ADD type_two_relatives_details varchar(255) default null;
ALTER TABLE child ADD malnutrition int(11) not null;
ALTER TABLE child ADD other_syndrome_additional_comment varchar(255) default null;
ALTER TABLE child ADD hba1c_method_other varchar(255) default null;


ALTER TABLE child_versions ADD blood_glucose_at_diagnosis int(11) not null;
ALTER TABLE child_versions ADD blood_glucose_value float default null;
ALTER TABLE child_versions ADD blood_glucose_units int(11) default null;
ALTER TABLE child_versions ADD hba1c_at_diagnosis int(11) not null;
ALTER TABLE child_versions ADD hba1c_percentage float default null;
ALTER TABLE child_versions ADD hba1c_method int(11) default null;
ALTER TABLE child_versions ADD ketoacidosis_at_diagnosis int(11) not null;
ALTER TABLE child_versions ADD polyuria_at_diagnosis int(11) not null;
ALTER TABLE child_versions ADD thirst_at_diagnosis int(11) not null;
ALTER TABLE child_versions ADD weight_loss_at_diagnosis int(11) not null;
ALTER TABLE child_versions ADD weight_at_diagnosis int(11) not null;
ALTER TABLE child_versions ADD weight_at_diagnosis_value float default null;
ALTER TABLE child_versions ADD height_at_diagnosis int(11) not null;
ALTER TABLE child_versions ADD height_at_diagnosis_value float default null;
ALTER TABLE child_versions ADD type_one_in_family int(11) not null;
ALTER TABLE child_versions ADD type_one_relatives_details varchar(255) default null;
ALTER TABLE child_versions ADD type_two_in_family int(11) not null;
ALTER TABLE child_versions ADD type_two_relatives_details varchar(255) default null;
ALTER TABLE child_versions ADD malnutrition int(11) not null;
ALTER TABLE child_versions ADD other_syndrome_additional_comment varchar(255) default null;
ALTER TABLE child_versions ADD hba1c_method_other varchar(255) default null;


update child set blood_glucose_at_diagnosis = 1;
update child set hba1c_at_diagnosis = 2;
update child set ketoacidosis_at_diagnosis = 3;
update child set polyuria_at_diagnosis = 2;
update child set thirst_at_diagnosis = 2;
update child set weight_loss_at_diagnosis = 2;
update child set weight_at_diagnosis = 1;
update child set height_at_diagnosis = 1;
update child set type_one_in_family = 2;
update child set type_two_in_family = 2;
update child set malnutrition = 2;

DROP TABLE child_versions;
CREATE TABLE child_versions LIKE child;
ALTER TABLE child_versions MODIFY COLUMN id BIGINT(20) NOT NULL, DROP PRIMARY KEY;
