package org.lifeforachild.domain;

public enum CauseOfDeathType {
	KETOACIDOSIS,
	HYPOGLYCAEMIA,
	OTHER_DIABETES_RELATED_CONDITION,
	UNRELATED_TO_DIABETES,
	INFECTION,
	UNKNOWN,
	COMBINATION_OF_CAUSES
}
