package org.lifeforachild.domain;

public enum MicroalbuminuriaUnitsType {
	MICROALBUMIN_MG_PER_L,
	MICROALBUMIN_G_PER_DL ,
	MICROALBUMIN_MCG_PER_MIN, 
	MICROALBUMIN_MG_PER_24HR, 
	ALBUMIN_CREATININE_RATIO_MG_ALB_PER_GM_CREAT, 
	ALBUMIN_CREATININE_RATIO_MG_ALB_PER_MMOL_CREAT}
