// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.lifeforachild.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.lifeforachild.domain.ChildDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ChildIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ChildIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ChildIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ChildIntegrationTest: @Transactional;
    
    @Autowired
    private ChildDataOnDemand ChildIntegrationTest.dod;
    
    @Test
    public void ChildIntegrationTest.testCountChildren() {
        org.junit.Assert.assertNotNull("Data on demand for 'Child' failed to initialize correctly", dod.getRandomChild());
        long count = org.lifeforachild.domain.Child.countChildren();
        org.junit.Assert.assertTrue("Counter for 'Child' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ChildIntegrationTest.testFindChild() {
        org.lifeforachild.domain.Child obj = dod.getRandomChild();
        org.junit.Assert.assertNotNull("Data on demand for 'Child' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Child' failed to provide an identifier", id);
        obj = org.lifeforachild.domain.Child.findChild(id);
        org.junit.Assert.assertNotNull("Find method for 'Child' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Child' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ChildIntegrationTest.testFindAllChildren() {
        org.junit.Assert.assertNotNull("Data on demand for 'Child' failed to initialize correctly", dod.getRandomChild());
        long count = org.lifeforachild.domain.Child.countChildren();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Child', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.lifeforachild.domain.Child> result = org.lifeforachild.domain.Child.findAllChildren();
        org.junit.Assert.assertNotNull("Find all method for 'Child' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Child' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ChildIntegrationTest.testFindChildEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Child' failed to initialize correctly", dod.getRandomChild());
        long count = org.lifeforachild.domain.Child.countChildren();
        if (count > 20) count = 20;
        java.util.List<org.lifeforachild.domain.Child> result = org.lifeforachild.domain.Child.findChildEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Child' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Child' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ChildIntegrationTest.testFlush() {
        org.lifeforachild.domain.Child obj = dod.getRandomChild();
        org.junit.Assert.assertNotNull("Data on demand for 'Child' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Child' failed to provide an identifier", id);
        obj = org.lifeforachild.domain.Child.findChild(id);
        org.junit.Assert.assertNotNull("Find method for 'Child' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyChild(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Child' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ChildIntegrationTest.testMerge() {
        org.lifeforachild.domain.Child obj = dod.getRandomChild();
        org.junit.Assert.assertNotNull("Data on demand for 'Child' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Child' failed to provide an identifier", id);
        obj = org.lifeforachild.domain.Child.findChild(id);
        boolean modified =  dod.modifyChild(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.merge();
        obj.flush();
        //org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Child' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ChildIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Child' failed to initialize correctly", dod.getRandomChild());
        org.lifeforachild.domain.Child obj = dod.getNewTransientChild(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Child' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Child' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Child' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ChildIntegrationTest.testRemove() {
        org.lifeforachild.domain.Child obj = dod.getRandomChild();
        org.junit.Assert.assertNotNull("Data on demand for 'Child' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Child' failed to provide an identifier", id);
        obj = org.lifeforachild.domain.Child.findChild(id);
        obj.setIsDeleted(true);
        obj.flush();
        org.junit.Assert.assertTrue("Failed to remove 'Child' with identifier '" + id + "'", org.lifeforachild.domain.Child.findChild(id).getIsDeleted());
    }
    
}
