// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.lifeforachild.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.lifeforachild.domain.ClinicalRecordDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ClinicalRecordIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ClinicalRecordIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ClinicalRecordIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ClinicalRecordIntegrationTest: @Transactional;
    
    @Autowired
    private ClinicalRecordDataOnDemand ClinicalRecordIntegrationTest.dod;
    
    @Test
    public void ClinicalRecordIntegrationTest.testCountClinicalRecords() {
        org.junit.Assert.assertNotNull("Data on demand for 'ClinicalRecord' failed to initialize correctly", dod.getRandomClinicalRecord());
        long count = org.lifeforachild.domain.ClinicalRecord.countClinicalRecords();
        org.junit.Assert.assertTrue("Counter for 'ClinicalRecord' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ClinicalRecordIntegrationTest.testFindClinicalRecord() {
        org.lifeforachild.domain.ClinicalRecord obj = dod.getRandomClinicalRecord();
        org.junit.Assert.assertNotNull("Data on demand for 'ClinicalRecord' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ClinicalRecord' failed to provide an identifier", id);
        obj = org.lifeforachild.domain.ClinicalRecord.findClinicalRecord(id);
        org.junit.Assert.assertNotNull("Find method for 'ClinicalRecord' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ClinicalRecord' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ClinicalRecordIntegrationTest.testFindAllClinicalRecords() {
        org.junit.Assert.assertNotNull("Data on demand for 'ClinicalRecord' failed to initialize correctly", dod.getRandomClinicalRecord());
        long count = org.lifeforachild.domain.ClinicalRecord.countClinicalRecords();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ClinicalRecord', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.lifeforachild.domain.ClinicalRecord> result = org.lifeforachild.domain.ClinicalRecord.findAllClinicalRecords();
        org.junit.Assert.assertNotNull("Find all method for 'ClinicalRecord' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ClinicalRecord' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ClinicalRecordIntegrationTest.testFindClinicalRecordEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ClinicalRecord' failed to initialize correctly", dod.getRandomClinicalRecord());
        long count = org.lifeforachild.domain.ClinicalRecord.countClinicalRecords();
        if (count > 20) count = 20;
        java.util.List<org.lifeforachild.domain.ClinicalRecord> result = org.lifeforachild.domain.ClinicalRecord.findClinicalRecordEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ClinicalRecord' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ClinicalRecord' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ClinicalRecordIntegrationTest.testFlush() {
        org.lifeforachild.domain.ClinicalRecord obj = dod.getRandomClinicalRecord();
        org.junit.Assert.assertNotNull("Data on demand for 'ClinicalRecord' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ClinicalRecord' failed to provide an identifier", id);
        obj = org.lifeforachild.domain.ClinicalRecord.findClinicalRecord(id);
        org.junit.Assert.assertNotNull("Find method for 'ClinicalRecord' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyClinicalRecord(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ClinicalRecord' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClinicalRecordIntegrationTest.testMerge() {
        org.lifeforachild.domain.ClinicalRecord obj = dod.getRandomClinicalRecord();
        org.junit.Assert.assertNotNull("Data on demand for 'ClinicalRecord' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ClinicalRecord' failed to provide an identifier", id);
        obj = org.lifeforachild.domain.ClinicalRecord.findClinicalRecord(id);
        boolean modified =  dod.modifyClinicalRecord(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.merge();
        obj.flush();
        //org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ClinicalRecord' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClinicalRecordIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ClinicalRecord' failed to initialize correctly", dod.getRandomClinicalRecord());
        org.lifeforachild.domain.ClinicalRecord obj = dod.getNewTransientClinicalRecord(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ClinicalRecord' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ClinicalRecord' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ClinicalRecord' identifier to no longer be null", obj.getId());
    }
    
    //@Test
    public void ClinicalRecordIntegrationTest.testRemove() {
        org.lifeforachild.domain.ClinicalRecord obj = dod.getRandomClinicalRecord();
        org.junit.Assert.assertNotNull("Data on demand for 'ClinicalRecord' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ClinicalRecord' failed to provide an identifier", id);
        obj = org.lifeforachild.domain.ClinicalRecord.findClinicalRecord(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ClinicalRecord' with identifier '" + id + "'", org.lifeforachild.domain.ClinicalRecord.findClinicalRecord(id));
    }
    
}
