// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.lifeforachild.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ClinicalRecordIntegrationTest_Roo_Configurable {
    
    declare @type: ClinicalRecordIntegrationTest: @Configurable;
    
}
