// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.lifeforachild.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.lifeforachild.domain.CountryDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CountryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CountryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CountryIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CountryIntegrationTest: @Transactional;
    
    @Autowired
    private CountryDataOnDemand CountryIntegrationTest.dod;
    
    @Test
    public void CountryIntegrationTest.testCountCountrys() {
        org.junit.Assert.assertNotNull("Data on demand for 'Country' failed to initialize correctly", dod.getRandomCountry());
        long count = org.lifeforachild.domain.Country.countCountrys();
        org.junit.Assert.assertTrue("Counter for 'Country' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CountryIntegrationTest.testFindCountry() {
        org.lifeforachild.domain.Country obj = dod.getRandomCountry();
        org.junit.Assert.assertNotNull("Data on demand for 'Country' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Country' failed to provide an identifier", id);
        obj = org.lifeforachild.domain.Country.findCountry(id);
        org.junit.Assert.assertNotNull("Find method for 'Country' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Country' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CountryIntegrationTest.testFindAllCountrys() {
        org.junit.Assert.assertNotNull("Data on demand for 'Country' failed to initialize correctly", dod.getRandomCountry());
        long count = org.lifeforachild.domain.Country.countCountrys();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Country', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.lifeforachild.domain.Country> result = org.lifeforachild.domain.Country.findAllCountrys();
        org.junit.Assert.assertNotNull("Find all method for 'Country' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Country' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CountryIntegrationTest.testFindCountryEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Country' failed to initialize correctly", dod.getRandomCountry());
        long count = org.lifeforachild.domain.Country.countCountrys();
        if (count > 20) count = 20;
        java.util.List<org.lifeforachild.domain.Country> result = org.lifeforachild.domain.Country.findCountryEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Country' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Country' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CountryIntegrationTest.testFlush() {
        org.lifeforachild.domain.Country obj = dod.getRandomCountry();
        org.junit.Assert.assertNotNull("Data on demand for 'Country' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Country' failed to provide an identifier", id);
        obj = org.lifeforachild.domain.Country.findCountry(id);
        org.junit.Assert.assertNotNull("Find method for 'Country' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCountry(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Country' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CountryIntegrationTest.testMerge() {
        org.lifeforachild.domain.Country obj = dod.getRandomCountry();
        org.junit.Assert.assertNotNull("Data on demand for 'Country' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Country' failed to provide an identifier", id);
        obj = org.lifeforachild.domain.Country.findCountry(id);
        boolean modified =  dod.modifyCountry(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.merge();
        obj.flush();
        //org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Country' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CountryIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Country' failed to initialize correctly", dod.getRandomCountry());
        org.lifeforachild.domain.Country obj = dod.getNewTransientCountry(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Country' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Country' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Country' identifier to no longer be null", obj.getId());
    }
    
    //@Test
    public void CountryIntegrationTest.testRemove() {
        org.lifeforachild.domain.Country obj = dod.getRandomCountry();
        org.junit.Assert.assertNotNull("Data on demand for 'Country' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Country' failed to provide an identifier", id);
        obj = org.lifeforachild.domain.Country.findCountry(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Country' with identifier '" + id + "'", org.lifeforachild.domain.Country.findCountry(id));
    }
    
}
