// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.lifeforachild.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.lifeforachild.domain.ReportDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ReportIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ReportIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ReportIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ReportIntegrationTest: @Transactional;
    
    @Autowired
    private ReportDataOnDemand ReportIntegrationTest.dod;
    
    @Test
    public void ReportIntegrationTest.testCountReports() {
        org.junit.Assert.assertNotNull("Data on demand for 'Report' failed to initialize correctly", dod.getRandomReport());
        long count = org.lifeforachild.domain.Report.countReports();
        org.junit.Assert.assertTrue("Counter for 'Report' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ReportIntegrationTest.testFindReport() {
        org.lifeforachild.domain.Report obj = dod.getRandomReport();
        org.junit.Assert.assertNotNull("Data on demand for 'Report' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Report' failed to provide an identifier", id);
        obj = org.lifeforachild.domain.Report.findReport(id);
        org.junit.Assert.assertNotNull("Find method for 'Report' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Report' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ReportIntegrationTest.testFindAllReports() {
        org.junit.Assert.assertNotNull("Data on demand for 'Report' failed to initialize correctly", dod.getRandomReport());
        long count = org.lifeforachild.domain.Report.countReports();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Report', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.lifeforachild.domain.Report> result = org.lifeforachild.domain.Report.findAllReports();
        org.junit.Assert.assertNotNull("Find all method for 'Report' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Report' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ReportIntegrationTest.testFindReportEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Report' failed to initialize correctly", dod.getRandomReport());
        long count = org.lifeforachild.domain.Report.countReports();
        if (count > 20) count = 20;
        java.util.List<org.lifeforachild.domain.Report> result = org.lifeforachild.domain.Report.findReportEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Report' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Report' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ReportIntegrationTest.testFlush() {
        org.lifeforachild.domain.Report obj = dod.getRandomReport();
        org.junit.Assert.assertNotNull("Data on demand for 'Report' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Report' failed to provide an identifier", id);
        obj = org.lifeforachild.domain.Report.findReport(id);
        org.junit.Assert.assertNotNull("Find method for 'Report' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyReport(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Report' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReportIntegrationTest.testMerge() {
        org.lifeforachild.domain.Report obj = dod.getRandomReport();
        org.junit.Assert.assertNotNull("Data on demand for 'Report' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Report' failed to provide an identifier", id);
        obj = org.lifeforachild.domain.Report.findReport(id);
        boolean modified =  dod.modifyReport(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.merge();
        obj.flush();
        //org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Report' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReportIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Report' failed to initialize correctly", dod.getRandomReport());
        org.lifeforachild.domain.Report obj = dod.getNewTransientReport(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Report' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Report' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Report' identifier to no longer be null", obj.getId());
    }
    
    //@Test
    public void ReportIntegrationTest.testRemove() {
        org.lifeforachild.domain.Report obj = dod.getRandomReport();
        org.junit.Assert.assertNotNull("Data on demand for 'Report' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Report' failed to provide an identifier", id);
        obj = org.lifeforachild.domain.Report.findReport(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Report' with identifier '" + id + "'", org.lifeforachild.domain.Report.findReport(id));
    }
    
}
