// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.lifeforachild.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.lifeforachild.util.TestUtil;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect UserDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserDataOnDemand: @Component;
    
    private Random UserDataOnDemand.rnd = new SecureRandom();
    
    private List<User> UserDataOnDemand.data;
    
    @Autowired
    private UserGroupDataOnDemand UserDataOnDemand.userGroupDataOnDemand;
    
    public User UserDataOnDemand.getNewTransientUser(int index) {
        User obj = new User();
        setCentre(obj, index);
        setCountry(obj, index);
        setCreatedBy(obj, index);
        setCreatedOn(obj, index);
        setEnabled(obj, index);
        setFirstName(obj, index);
        setIsDeleted(obj, index);
        setLastName(obj, index);
        setOldPassword(obj, index);
        setOldUsername(obj, index);
        setPassword(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedOn(obj, index);
        setUserGroup(obj, index);
        setUsername(obj, index);
        return obj;
    }
    
    public void UserDataOnDemand.setCentre(User obj, int index) {
        DiabetesCentre centre = null;
        obj.setCentre(centre);
    }
    
    public void UserDataOnDemand.setCountry(User obj, int index) {
        Country country = null;
        obj.setCountry(country);
    }
    
    public void UserDataOnDemand.setCreatedBy(User obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void UserDataOnDemand.setCreatedOn(User obj, int index) {
        Date createdOn = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedOn(createdOn);
    }
    
    public void UserDataOnDemand.setEnabled(User obj, int index) {
        Boolean enabled = true;
        obj.setEnabled(enabled);
    }
    
    public void UserDataOnDemand.setFirstName(User obj, int index) {
        String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    public void UserDataOnDemand.setIsDeleted(User obj, int index) {
        Boolean isDeleted = true;
        obj.setIsDeleted(isDeleted);
    }
    
    public void UserDataOnDemand.setLastName(User obj, int index) {
        String lastName = "lastName_" + index;
        obj.setLastName(lastName);
    }
    
    public void UserDataOnDemand.setOldPassword(User obj, int index) {
        String oldPassword = "oldPassword_" + index;
        obj.setOldPassword(oldPassword);
    }
    
    public void UserDataOnDemand.setOldUsername(User obj, int index) {
        String oldUsername = "oldUsername_" + index;
        obj.setOldUsername(oldUsername);
    }
    
    public void UserDataOnDemand.setPassword(User obj, int index) {
        String password = "password_" + index;
        obj.setPassword(password);
    }
    
    public void UserDataOnDemand.setUpdatedBy(User obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void UserDataOnDemand.setUpdatedOn(User obj, int index) {
        Date updatedOn = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedOn(updatedOn);
    }
    
    public void UserDataOnDemand.setUserGroup(User obj, int index) {
        UserGroup userGroup = userGroupDataOnDemand.getRandomUserGroup();
        obj.setUserGroup(userGroup);
    }
    
    public void UserDataOnDemand.setUsername(User obj, int index) {
        String username = "username_" + index;
        obj.setUsername(username);
    }
    
    public User UserDataOnDemand.getSpecificUser(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        User obj = data.get(index);
        return User.findUser(obj.getId());
    }
    
    public User UserDataOnDemand.getRandomUser() {
        init();
        User obj = data.get(rnd.nextInt(data.size()));
        return User.findUser(obj.getId());
    }
    
    public boolean UserDataOnDemand.modifyUser(User obj) {
        return false;
    }
    
    public void UserDataOnDemand.init() {
    	TestUtil.createAndSetTestUser();
        data = User.findUserEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'User' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.lifeforachild.domain.User>();
        for (int i = 0; i < 10; i++) {
            User obj = getNewTransientUser(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
